# Generated by Django 5.1.1 on 2024-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book_outlet", "0007_country_alter_address_options_book_published_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="published_country",
            field=models.ManyToManyField(null=True, to="book_outlet.country"),
        ),
    ]
