# Generated by Django 5.1.1 on 2024-09-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yourblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(
                blank=True, error_messages="이메일 주소를 확인해 주세요.", max_length=100
            ),
        ),
    ]
