# Generated by Django 5.1.1 on 2024-09-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yourblog", "0002_alter_author_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(blank=True, to="yourblog.tag"),
        ),
    ]
