# Generated by Django 5.1.1 on 2024-09-28 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yourblog", "0003_alter_author_email_alter_post_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="exceprt",
            new_name="excerpt",
        ),
    ]
