# Generated by Django 5.1.1 on 2024-10-03 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pd_type",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("pd_name", models.CharField(max_length=20)),
                ("pd_note", models.CharField(blank=True, max_length=200)),
                ("pd_price", models.IntegerField()),
                ("pd_img", models.ImageField(upload_to="pd_images")),
            ],
        ),
    ]
